"""per-account safe to spend threshold

Revision ID: 583d6357b1f7
Revises: f09760e2fcfb
Create Date: 2026-08-06 11:25:25.524845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '583d6357b1f7'
down_revision: Union[str, Sequence[str], None] = 'f09760e2fcfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('safeToSpendThresholdCent', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('accounts', 'safeToSpendThresholdCent', server_default=None)
    op.drop_column('profiles', 'safeToSpendThresholdCent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('safeToSpendThresholdCent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'safeToSpendThresholdCent')
    # ### end Alembic commands ###
