"""add cursor to plaiditem

Revision ID: 7a616d8cb7fb
Revises: bdae0f9af19b
Create Date: 2026-07-27 23:56:35.282810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a616d8cb7fb'
down_revision: Union[str, Sequence[str], None] = 'bdae0f9af19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaiditem', sa.Column('cursor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaiditem', 'cursor')
    # ### end Alembic commands ###
