"""add safe to spend threshold to profiles

Revision ID: 9952bebc9d75
Revises: a95c558bf9ad
Create Date: 2026-07-29 19:33:11.748186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9952bebc9d75'
down_revision: Union[str, Sequence[str], None] = 'a95c558bf9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('safeToSpendThresholdCent', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'safeToSpendThresholdCent')
    # ### end Alembic commands ###
