"""add_last_synced_at_to_plaid_item

Revision ID: a66bfbbbca58
Revises: a5fcdbf17f09
Create Date: 2026-08-26 14:33:26.486635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a66bfbbbca58'
down_revision: Union[str, Sequence[str], None] = 'a5fcdbf17f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaiditem', sa.Column('lastSyncedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaiditem', 'lastSyncedAt')
    # ### end Alembic commands ###
