"""add layoutId to profiles

Revision ID: bdae0f9af19b
Revises: ec4516afa314
Create Date: 2026-07-25 17:35:53.453254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bdae0f9af19b'
down_revision: Union[str, Sequence[str], None] = 'ec4516afa314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('layoutId', sqlmodel.sql.sqltypes.AutoString(), nullable=False,server_default='horizontal'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'layoutId')
    # ### end Alembic commands ###
