"""initial schema

Revision ID: ec4516afa314
Revises: 
Create Date: 2026-07-25 08:48:19.266961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec4516afa314'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('targetToCent', sa.Integer(), nullable=False),
    sa.Column('currentToCent', sa.Integer(), nullable=False),
    sa.Column('targetDate', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bucket_userId'), 'bucket', ['userId'], unique=False)
    op.create_table('plaiditem',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accessTokenEncrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('itemId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instituionName', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', 'loginReq', 'error', name='status'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plaiditem_itemId'), 'plaiditem', ['itemId'], unique=True)
    op.create_index(op.f('ix_plaiditem_userId'), 'plaiditem', ['userId'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('themeId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_userId'), 'profiles', ['userId'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plaidItemId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plaidAccountId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('checking', 'saving', 'credit', name='type'), nullable=False),
    sa.Column('currentBalanceToCent', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plaidItemId'], ['plaiditem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_plaidAccountId'), 'accounts', ['plaidAccountId'], unique=True)
    op.create_index(op.f('ix_accounts_userId'), 'accounts', ['userId'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accountId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plaidTransactionId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dateOf', sa.Date(), nullable=False),
    sa.Column('amountToCent', sa.Integer(), nullable=False),
    sa.Column('merchantName', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('isAnomaly', sa.Boolean(), nullable=False),
    sa.Column('isManual', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accountId'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_accountId'), 'transactions', ['accountId'], unique=False)
    op.create_index(op.f('ix_transactions_dateOf'), 'transactions', ['dateOf'], unique=False)
    op.create_index(op.f('ix_transactions_plaidTransactionId'), 'transactions', ['plaidTransactionId'], unique=True)
    op.create_index(op.f('ix_transactions_userId'), 'transactions', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_userId'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_plaidTransactionId'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_dateOf'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_accountId'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_accounts_userId'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_plaidAccountId'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_profiles_userId'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_plaiditem_userId'), table_name='plaiditem')
    op.drop_index(op.f('ix_plaiditem_itemId'), table_name='plaiditem')
    op.drop_table('plaiditem')
    op.drop_index(op.f('ix_bucket_userId'), table_name='bucket')
    op.drop_table('bucket')
    # ### end Alembic commands ###
